### PR TITLE
Respond with non-OK HTTP status codes on error

### LINKED ISSUE #14: Respond with appropriate HTTP code on error
**Description**

The server currently responds with status code 200 on all requests, even if they fail.

**Steps to Reproduce**

Trigger any error, like query a block by an invalid hash.

**Expected Result**

The response is not a 200.

**Actual Result**

The response is a 200. The body contents of the response is correct.

Example:

```
$ curl -v -Hcontent-type:application/json localhost:8080/block -d '{"network_identifier":{"blockchain":"concordium","network":"testnet"}, "block_identifier":{"hash":"123"}}' | jq .
*   Trying ::1:8080...
* connect to ::1 port 8080 failed: Connection refused
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /block HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.74.0
> Accept: */*
> content-type:application/json
> Content-Length: 105
> 
} [105 bytes data]
* upload completely sent off: 105 out of 105 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< content-type: application/json
< content-length: 245
< date: Tue, 03 May 2022 13:21:34 GMT
< 
{ [245 bytes data]
* Connection #0 to host localhost left intact
{
  "code": 1200,
  "message": "invalid input: invalid value or identifier",
  "description": "The provided value or identifier is incorrectly typed or formatted.",
  "retriable": false,
  "details": {
    "message": "invalid hash value '123'",
    "name": "block identifier"
  }
}
```

**Versions**
- Software Version: 0.1.1

### PR DESCRIPTION
**Pull request by bisgardo**
## Purpose

Make it easier for clients to understand when the response is an error. Currently they can only do it by parsing the JSON payload.

## Changes

Respond with non-OK HTTP status codes on error. The status code also includes a hint on what kind of error it is.

Resolves #14.

### CODE REVIEW

File: src/handler_error.rs [hunk 1]
```diff
@@ -41,125 +41,171 @@ pub async fn handle_rejection(rej: Rejection) -> Result<impl Reply, Rejection> {
...
+                reply::json(&invalid_input_unsupported_field_error(Some(
+                    "sub_account".to_string(),
+                ))),
+                StatusCode::BAD_REQUEST,
+            ),
+            ApiError::RequiredFieldMissing(name) => reply::with_status(
+                reply::json(&invalid_input_missing_field_error(Some(name.to_string()))),
+                StatusCode::BAD_REQUEST,
+            ),
+            ApiError::InvalidAccountAddress(addr) => reply::with_status(
```
Comment (abizjak) [inline src/handler_error.rs:59]: The examples in the documentation https://www.rosetta-api.org/docs/AccountApi.html#500---error seem to show error 500 for this error, but also all the other errors that I've checked (by going through examples).

Not sure why they chose that, since BAD_REQUEST does make sense in this case, but seeing that they did choose it, shouldn't we follow that choice?

Comment (bisgardo) [reply src/handler_error.rs:59]: Hm I never noticed that... They really don't seem to care about HTTP. I'll check/ask their forum if they have an official opinion.

Comment (abizjak) [reply src/handler_error.rs:59]: Ok. Let's wait with merging this until there you've done that.

Comment (bisgardo) [reply src/handler_error.rs:59]: https://community.rosetta-api.org/t/http-status-codes/736

Comment (bisgardo) [reply src/handler_error.rs:59]: @abizjak I guess we aren't going to get a response to that complex question. So what do we do?

Given the time that I've already spent and the fact that I consider it correct, I would prefer merging this as it is. But I would also be fine with changing it to all 500...

Comment (abizjak) [reply src/handler_error.rs:59]: Can we put a short section in the README explaining the choice of the more precise error codes, as opposed to 500 which the examples show?

With that, I think we can merge this.

File: README.md [hunk 2]
```diff
@@ -217,6 +217,12 @@ For consistency, operation type names are styled with snake_case.
 
 The Construction API only supports operations of type `transfer`.
 
+### Errors
+
+All success responses are returned with an HTTP 200 message.
+Errors are returned with an appropriate 4xx code if they're the result of by client input.
```
Comment (abizjak) [inline README.md:223]:
```suggestion
Errors are returned with an appropriate 4xx code if they're the result of the client input.
```
